### ISSUE TITLE
Searching for a building only displays the building info page

### ISSUE THREAD

**Issue by Luigi-PastorePica** [jkon1513/ASE2018#48] opened 2018-12-09 21:47 UTC
If the search matches a building, the information page for the building is shown, but there is no option to go to the map and see the location of the building. Tapping the Android back button takes user back to the map, but does not show the building marker.

**Comment by jkon1513** [comment] 2018-12-09 23:13
again, this is the intended behavior. if you would like to navigate to a building you click the "navigate" button on the building page.

**Comment by jkon1513** [comment] 2018-12-09 23:30
as an update: it seems this issue in phone dependent. works on a nexus and pixel emulator as well as a live galaxy s8+. will look into how to deal with this.

**Comment by jkon1513** [comment] 2018-12-14 02:44
this should be fixed by #57

**Closed** 2018-12-14 04:19 UTC
